# Generated by Django 5.2.12 on 2026-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='dues_status',
            field=models.CharField(blank=True, default='Bekliyor', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='joined_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Üye'), ('board', 'Yönetim'), ('admin', 'Admin')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='tcno',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('pending', 'Başvuru')], default='pending', max_length=20),
        ),
    ]
